import Image from "next/image";
import CloseIcon from "@/public/close-lg-svgrepo-com.svg";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import RightNav from '@/components/RightNav'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div
          className={`${robotoCondensed.className} h-screen p-4 dark:bg-black overflow-hidden`}
        >
          <main className="h-full">
            <div className="h-full bg-[#202020] text-center sm:text-left">
              <div className="flex w-full h-full">
                <div className="w-1/6 h-full flex flex-col">
                  <div className="flex justify-center">
                    <Image
                      src="/logo.svg"
                      alt=""
                      width={1000}
                      height={1000}
                      className="p-12"
                    />
                  </div>

                  <button className="mt-auto flex flex-col p-12">
                    <Image
                      src="/launchIcon.svg"
                      alt=""
                      width={500}
                      height={500}
                      className="w-1/4 mx-auto mb-6"
                    />
                    <span>
                      let me launch <br></br>your idea
                    </span>
                  </button>
                </div>

                <div className="w-4/6 h-full flex flex-col bg-[#242424] overflow-auto no-scrollbar">
                  {children}
                </div>

                <RightNav />                
              </div>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
